on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - names: "Login to docker hub"
        run: docker login --username gannaadel --password dckr_pat_vUCFHZ3jRXTwQZKT7qP4Gk34KtM