on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - names: "login to docker hub"
        run: docker login --username gannaadel --password dckr_pat_wXG7-ZP8z5qNMackjPKPjlFsbsE